styles/linter-ui.less

Not sure if this is future proof, since it uses the `gutter-name="linter-ui-default"` attribute selector. Will there be something like `linter-ui-custom` or so? Then it won't work. Well, I guess the custom UI styles would need to do the same.

Enable linter tooltips to overflow

---

lib/editor.js

Currently the bubble is not removed if the cursor keeps moving. It is removed 200ms **after the cursor stops moving**. This PR makes sure the bubble is removed as soon as possible, adding the bubble remains the same way

Remove bubbles even when the cursor keeps moving

---

lib/buffer.js

Now it only accepts 0 for a line number on an updated marker if the last line number was zero as well, this prevents destruction of the message range when the marker is being destroyed.
Normally the it doesn't matter what happens to a message after the editor it is pointing to is closed, but in the case of project scoped linters we have to restart/reload the Editor to fix it
Fixes #58

Do not disrupt message position when buffer is destroyed

---

CHANGELOG.md
lib/helpers.js
spec/helpers-spec.js

It's gonna be a callback that has the message as the first parameter so it works with arrow functions
Fixes https://github.com/steelbrain/linter/issues/1106

Support selected attribute for messages

---

lib/elements/message.js
styles/linter-ui.less

add clipboard icon to linter messages

---

package.json

The current scripts completely fail on Windows, bring in `rimraf` as a `devDependency` to allow cross-platform cleaning of the lib folder.

Use rimraf for scripts

---

styles/linter-ui.less

The status indicator has a inconsistent border radius.
With the One Light theme this is hardly noticeable, but with the One Dark theme this is quite prominent.
**master**
**PR**

Fix: Inconsistent border-radius of status indicator

---

.eslintrc.json
decls/atom.js
decls/jasmine.js
lib/busy-signal.js
lib/commands.js
lib/editor/index.js
lib/editors.js
lib/index.js
lib/main.js
lib/panel/delegate.js
lib/panel/index.js
lib/status-bar/element.js
lib/status-bar/index.js
lib/tooltip/delegate.js
lib/tooltip/index.js
lib/tree-view/index.js
package.json
spec/.eslintrc.json

Defer several actions currently being done in package activation till an idle time. The has the effect of pushing the massive requires of React and ReactDOM off to the idle time as the main activation doesn't require them.
On my system on a blank profile (`linter`, `linter-ui-default`, `busy-signal`, `intentions` the only non-core packages) this brings the average "activation" time from 311 ms down to 16.8 ms, or in other words a speed up of ~18.5x. It's possible with a major refactor this could be brought down further, but for now this should be a decent improvement.
Fixes #226.

Reduce activation time

---

CHANGELOG.md
styles/linter-ui.less

While it's an upstream issue, we can proof it here
Ref: https://github.com/facebook/nuclide/issues/1117

Proofing for Nuclide's Tree View Issue

---

CHANGELOG.md
lib/helpers.js
lib/main.js
lib/panel/component.js
lib/panel/delegate.js
lib/panel/dock.js
lib/panel/index.js
package.json

Use Docks API

---

CHANGELOG.md
lib/editors.js

Fixes https://github.com/steelbrain/linter-ui-default/issues/225
⚠️   This will also mean that it'll remove tooltip when we click on any other dock even Linter's own ⚠️

Remove Editor tooltip when unfocused

---

CHANGELOG.md
lib/panel/index.js
package.json

Unfortunately, monitoring the active pane becomes *very* tricky with the new Docks
Because clicking on another dock makes it a pane item and we have to hide the linter panel when user clicks at say the new github dock.
Removing this behavior seems like the way forward
Fixes #294

Remove hidePanelUnlessTextEditor config

---

CHANGELOG.md
lib/panel/index.js

Previously we were destroying and re-creating a pane item for Linter on hide/show config change
That was messy because it would focus the linter dock each time it would open, tho we were refocusing the text editor it would still make the UI feel laggy and wasn't the best ever experience
Now what we're doing is that we're telling Atom to open it in a pane container, and do not focus the Item or the pane container, and then we're showing the pane container ourselves without focusing it
This makes sure that the ui indicators are the bottom are not hidden then shown because there's no switch of Active Pane Item

Cleanup dock hiding implementation

---

CHANGELOG.md
styles/linter-ui.less

Too many themes had the previous color variable as transparent
Atom Dark
Atom Light
Atom Material
Nord Atom
One Dark
One Light
Apex

Fix tooltips background

---

styles/linter-ui.less

Fix tooltip border for multiple messages

---

lib/helpers.js
lib/tooltip/message.js

the url of these links have to look like `atom://linter/<file>?row=<number>&column=<number>` where
* `file` is the absolute path to the file
* `row` and `column` are optional and will jump to this position in the editor
Required by: https://github.com/steelbrain/flow-ide/pull/94

allow links in markdown that opens a file in atom

---

lib/busy-signal.js
spec/busy-singal-spec.js
spec/helpers.js

Split the timing data for providers out into individual items so they are no longer grouped together randomly.
Fixes https://github.com/steelbrain/linter/issues/1442.

Show provider times individually

---

styles/linter-ui.less

In the latest version (at the time of posting) the gutter markers are showing and working. There is only one problem I noticed. This may be a little picky but the marker isn't in the middle of its column. This is a simple fix with a single css addition.
#
Before the change:
After the change:
#
Version tested on:
````
Atom    : 1.21.0-dev-98296bf 
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
````

Position the gutter marker in the middle

---

lib/editor/index.js

Fixes https://github.com/steelbrain/linter-ui-default/issues/415
Removed the debounce because it's keyboard and not mouse, debounce is not necessary, the operation is sync but happens very quickly so is unnoticable

Fix race condition where tooltip would cover autocomplete

---

lib/editor/index.js
package.json
styles/linter-ui.less

Use the new `text` decoration style introduced in Atom v1.19.0 in order to properly decorate the text of a range as the old `highlight` style was actually a fluke that it was working at all.
Before:
_Note the gap in the blank highlighted area._
After:
Suggested by @as-cii in https://github.com/atom/atom/issues/15508#issuecomment-327130261.

Utilize the new text decoration style

---

lib/status-bar/element.js
lib/status-bar/helpers.js
styles/linter-ui.less

Simplify how the status bar icons are being generated, bringing them inline with how other status bar "widgets" are using similar icons.
Examples:
UI | Syntax | Result
-- | ------ | ------
One Dark | One Dark | ![image](https://user-images.githubusercontent.com/427137/30496763-4a4abf46-9a05-11e7-9f00-e7dfb70dc8e2.png)
One Light | One Light | ![image](https://user-images.githubusercontent.com/427137/30496805-6e931970-9a05-11e7-84eb-5411c8509a1a.png)
Atom Material | One Dark | ![image](https://user-images.githubusercontent.com/427137/30496887-ab4c72e4-9a05-11e7-8bd0-a0e3a9149736.png)
Atom Material | One Light | ![image](https://user-images.githubusercontent.com/427137/30496848-8f2171a0-9a05-11e7-89eb-d4adb37c7dc7.png)
Fixes #437.
Closes #438.

Simplify and fix alignment of status bar icons

---

styles/linter-ui.less

Line length based off this article, which suggests 21em-30em for readability. Added a few ems just in case.
http://maxdesign.com.au/articles/ideal-line-length-in-ems/

Set max-width for linter tooltip for readability.

---

CHANGELOG.md
lib/panel/dock.js
lib/panel/index.js
package.json

I really really hate this way of doing it, but it was the only way I found. CSS methods don't work because linter's parent element (which takes all the height even if linter's panel doesn't) is an `absolute` div and they don't support taking minimum heights :(
Fixes #332
Fixes #331

Add alwaysTakeMinimumSpace to new dock panel

---

lib/panel/index.js

Improve showPanelConfig consistency when user interacts with BottomDock "externally" ( using Atom features, as changing active tab or hidding the Dock )
Take into account BottomDock active pane item when toggle the panel 
This PR potentially fixes : 
#425 
#518 
#537 
#547

Handle BottomDock active pane item and improve showPanelConfig consistence

---

lib/panel/index.js

prevent stealing focus from other panes in dock when adding items to the bottom dock.
fixes #582

prevent stealing focus from other panes

---

package.json
spec/busy-singal-spec.js
spec/editor-spec.js

This speeds up loading of Atom, by deferring the loading of linter-ui until the core Atom shell is loaded.

Adds activation hook

---

styles/linter-ui.less

This uses the invert of background color for the selected linter messages in the editor. As you see, the text has more contrast with its background which makes it easier to read.
Demo for a bunch of themes:
One Dark - Atom Dark
Atom Light - Atom light
Atom Dark - Atom Dark
One Dark - One Dark

use of background color inversion for linter messages

---

lib/editor/index.js
lib/helpers.js
lib/tooltip/index.js

By merging https://github.com/steelbrain/linter/pull/1706 the removal now works correctly. However, that reveals some bugs in the linter-ui code which is supposed to be fixed in this pull request. The previous logic of the linter mostly rerendered all the messages from scratch. But now some are needed to be removed and that is why these bugs got revealed.
In this PR, the rendering algorithm is rewritten so only the "added" messages are rendered from scratch, and the "removed" messages are removed. It does not render all the messages every time. This greatly improves performance.
Several memory leaks were fixed in this PR.

Rewrite rendering algorithm+ improve performance + fix memory leaks

---

lib/editors.js

This adds an array check for the error in #573. I can't reproduce this anymore in the new version, but it is good to add the check anyways.
Fixes https://github.com/steelbrain/linter-ui-default/issues/573

Array check guard in editors for removed/added

---

lib/tooltip/index.tsx
styles/linter-ui.less

- Fixes overlaps with datatips (linter messages now are positioned above the point, unless there is not enough space)
- Changes the style of the tooltips so they match datatips (atom-ide-community style)
info:
error:
when above the page, it does not translate:
Fixes https://github.com/atom-ide-community/atom-ide-datatip/issues/90

Fix DataTip conflicts

---

CHANGELOG.md
README.md
lib/tooltip/fix-button.tsx
lib/tooltip/message.tsx
styles/linter-ui.less

This redesigns the linter tooltip. 
The goals and requirements:
- The tooltips should look similar to datatips
- Respecting the data: 
- separate fix buttons, reference buttons, etc. for each message that can come from different providers
- Fast to use: 
- fix button should be on the left so the users can quickly click on it (based on their muscle memory) without the need for moving the mouse to the far right
- less-used buttons (like URL button) are placed on the right to prevent visual cluttering 
- Minimum empty space

Tooltip Redesign

---

lib/tooltip/index.tsx
package.json
pnpm-lock.yaml

- It is native, so faster.
- Supports MacOS (cmd+c)
- In addition to performance benefits, it also fixes the jumps that happened in the linter when you wanted to copy the text

fix: use native copy handling in tooltips

---

CHANGELOG.md
lib/tooltip/index.tsx

Normally, Linter tooltip is rendered above the line, but if there is not enough space it will move below the datatip.

fix: move the linter tooltip down when there is not enough space on top

---

package.json
pnpm-lock.yaml

In accordance to changes made in atom-package-deps.

:bug: fix: bump atom-package-deps to support spaced paths on Windows

---

.eslintrc.json
babel.config.json
lib/editor/helpers.ts
lib/tooltip/index.tsx
lib/tooltip/message.tsx
package.json
pnpm-lock.yaml

Fix rendering issues:
- Bump solid
- Add TooltipElement
- Bump solid-simple-table
Reduce bundle size:
- Lazy load Marked only if needed
- Add aliases for the dependencies so their esm version is used and bundled with Parcel

fix: fix rendering issues with the recent solid versions - reduce bundle size

---

lib/helpers.ts

I found out that if I had a file with linter warnings, when I opened up a new file, this new, empty file would be decorated as if **every line** had a linter error (example below - notice that it also confuses the UI, as it now thinks that the error is on the _first line_).
So I found that, in `filterMessages`, we get all messages and always add the message in the editor if `filePath` is not defined. This seems weird, and removing that line solves the issue, so I'm proposing this change. Let me know if there's something extra that I need to be aware of
Fixes #667

Don't propagate messages if filePath is undefined
