lib/elements/bubble.js
lib/elements/message.js
lib/main.js

Also null out some unused variables

Add link support to messages

---

lib/elements/message.js
lib/index.js

Fixes AtomLinter/linter-ui-default#5

Add showProviderNames config

---

lib/main.js

Fixes AtomLinter/linter-ui-default#4

Initialize panel with existing errors

---

lib/main.js
lib/panel.js

Beep Beep
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/linter-ui-default/9)

Fix status icon

---

lib/editor.js
lib/elements/bubble.js

Fixes AtomLinter/linter-ui-default#10
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/linter-ui-default/11)

Support traces in bubbles

---

lib/editor.js

Fixes https://github.com/AtomLinter/linter-ui-default/issues/12
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/linter-ui-default/13)

Show all available messages in bubble

---

lib/commands.js
lib/main.js

Add toggle-panel command

---

README.md

Beep Beep
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/linter-ui-default/24)

Tweak installation instructions

---

styles/linter-ui.less

Fixes https://github.com/AtomLinter/linter-ui-default/issues/18

Align toggle button

---

styles/linter-ui.less

Fixes https://github.com/AtomLinter/linter-ui-default/issues/17

Handle alignment issue in linter messages

---

styles/linter-ui.less

Minor UI changes

---

styles/linter-ui.less

Reverts AtomLinter/linter-ui-default#29

Revert linter message alignment fix

---

CHANGELOG.md
lib/editor.js

Fix a bug where editor listener would never be destroyed

---

lib/editor.js
lib/elements/message.js

Required since https://github.com/atom-community/linter/commit/87e0f4dc24d142935001f8f45256e84f04fefd3a

Fix compatibility with latest linter

---

lib/editor.js
lib/elements/message.js
lib/helpers.js

Linter will no longer be keeping UI packages in a fairy world, it now hands over them the raw messages it gets from providers

Handle raw messages instead of processed messages

---

styles/linter-ui.less

Save some pixels
cc @steelbrain

Make linter panel more compact

---

lib/index.js
lib/intentions.js
lib/main.js
lib/types.js
package.json

Fixes #44
Fixes atom-community/linter#1049

Implement fix API using intentions:list API

---

lib/busy-signal.js
lib/index.js
lib/main.js
package.json

Fixes https://github.com/AtomLinter/linter-ui-default/issues/53

Integrate with busy-signal

---

lib/elements/panel-messages.js
lib/helpers.js

Fixes https://github.com/AtomLinter/linter-ui-default/issues/33

Implement copy to clipboard in panel

---

lib/panel.js
package.json
spec/panel-spec.js

Fixes https://github.com/steelbrain/linter-ui-default/issues/43

Add messageTypesToIgnoreInPanel config

---

.eslintrc.json
lib/buffers.js
lib/commands.js
lib/helpers.js
lib/main.js
spec/.eslintrc.json
spec/commands-spec.js
spec/helpers.js

It jumps between errors in the current file, both forward and backward, in proper sorted order.
Fixes #46
Fixes steelbrain/linter#1033
Fixes steelbrain/linter#833

Implement commands

---

lib/editor.js

Handle gutter destruction error

---

CHANGELOG.md
lib/editor.js
package.json
spec/editor-spec.js
spec/helpers.js

To restore the previous linter tooltip behavior
Fixes #80
Todo

Add tooltipFollows config

---

CHANGELOG.md
lib/editor.js
spec/editor-spec.js

Hide tooltips if cursor is not exactly on line

---

styles/linter-ui.less

Fixes https://github.com/steelbrain/linter/issues/1151

Make gutter transparent

---

CHANGELOG.md
lib/editor.js
lib/editors.js
lib/elements/panel-messages.js
lib/main.js
package.json
spec/editor-spec.js

The purpose of this PR is to allow apply live config changes to the package

Observe configs

---

CHANGELOG.md
lib/editor.js
lib/elements/message.js
lib/helpers.js
lib/types.js
styles/linter-ui.less

Use the new  attribute to style messages

---

src/intentions.js
src/types.js

Add ability to have custom apply function in v2 message solutions.
Result of PR suggestion in #99

Add apply function to solution

---

styles/linter-ui.less

Using the UI variables rather than using own styles.

Tooltip style improvements

---

src/main.js
src/tree-view/index.js

Optimize TreeView decorations

---

package.json
src/editor/index.js
src/panel/index.js

Should've done it in the Greenkeeper PR

Upgrade to sb-event-kit@3

---

src/elements/helpers.js
src/elements/tooltip.js
src/helpers.js

Add support for v1 traces

---

src/helpers.js

Fix sorting by line number

---

src/panel/element.js

Display 0-indexed row and column properly

---

src/commands.js
src/helpers.js
src/intentions.js
src/types.js

Add apply all solutions command

---

lib/panel/component.js
styles/bottom-panel.less

Fix scroll in panel

---

.eslintignore
lib/elements/message-legacy.js
lib/elements/message.js
lib/index.js
lib/panel/component.js
lib/status-bar/index.js

We forgot to remove the `lib` ignore rule from eslint when we removed babel compilation. This PR fixes it

Fix ESLint not running

---

lib/commands.js
lib/panel/component.js

Make copy work in panel

---

lib/editor/index.js

Make tooltip toggle config work

---

lib/panel/component.js
lib/panel/delegate.js
lib/panel/index.js

Fixes https://github.com/steelbrain/linter-ui-default/issues/176

Take zero height when panel is hidden

---

CHANGELOG.md
lib/status-bar/index.js
package.json

Fixes https://github.com/steelbrain/linter-ui-default/issues/175

Add option to configure status bar position

---

CHANGELOG.md
lib/helpers.js
lib/panel/delegate.js
package.json

Add support for Current Line in panelRepresents config

---

CHANGELOG.md
lib/status-bar/index.js

Fixes https://github.com/steelbrain/linter/issues/1356

Move the statusbar to the left of line:col view

---

CHANGELOG.md
lib/helpers.js

Fix Current Line filter for array-like objects

---

CHANGELOG.md
lib/panel/delegate.js
lib/status-bar/element.js
lib/status-bar/index.js
lib/tree-view/index.js
package.json
styles/linter-ui.less

Fixes https://github.com/steelbrain/linter-ui-default/issues/181

Add config to hide status bar

---

CHANGELOG.md
lib/panel/component.js

Hide file column when panel represents current file

---

CHANGELOG.md
lib/editor/index.js
styles/linter-ui.less

Remove gutter container transparency

---

CHANGELOG.md
lib/editor/helpers.js

Fixes steelbrain/linter-ui-default#191

Validates ranges in case of NaN

---

CHANGELOG.md
package.json

Ref https://github.com/steelbrain/react-table/issues/7

Upgrade sb-react-table

---

CHANGELOG.md
lib/tree-view/helpers.js

Fixes https://github.com/steelbrain/linter-ui-default/issues/208

Fix a crash in TreeView handling a file outside Project Path

---

CHANGELOG.md
lib/editor/index.js

Fix mouse tooltip for some users

---

CHANGELOG.md
lib/busy-signal.js
lib/index.js
package.json
spec/busy-singal-spec.js

Fixes https://github.com/steelbrain/linter/issues/1355

Make busy signal integration optional

---

.eslintrc.json
lib/panel/component.js
lib/tooltip/index.js
lib/tooltip/message-legacy.js
lib/tooltip/message.js
lib/tree-view/index.js
package.json

Upgrade to latest ESLint config

---

CHANGELOG.md
lib/panel/component.js

Make description in Bottom Panel clickable

---

CHANGELOG.md
styles/bottom-panel.less

Fixes https://github.com/steelbrain/linter-ui-default/issues/237

Fix two borders on Bottom Panel

---

CHANGELOG.md
styles/linter-ui.less

Use wavy underlines

---

CHANGELOG.md
lib/editor/helpers.js
lib/editor/index.js

Fixes steelbrain/linter#1421
Changes include 
- incased delay by 100ms
- expanded radius that tooltip is not hidden into
- take line height into account for vertical dimensions instead of a hard coded value

Improve tooltip hiding logic

---

CHANGELOG.md
lib/helpers.js
lib/tooltip/message-legacy.js
lib/tooltip/message.js

Only show url icon on tooltip if specified by linter provider

---

CHANGELOG.md
lib/editor/index.js

As advertised
Before:
After:
Fixes https://github.com/steelbrain/linter-ui-default/issues/238

Fix current line marker in gutter for soft wraps

---

CHANGELOG.md
styles/bottom-panel.less

Use theme variable for Bottom Panel font size

---

lib/busy-signal.js
lib/commands.js
lib/editor/index.js
lib/intentions.js
lib/main.js
lib/panel/component.js
lib/panel/delegate.js
lib/status-bar/element.js
lib/status-bar/index.js
lib/tooltip/delegate.js
lib/tooltip/index.js
lib/tooltip/message-legacy.js
lib/tooltip/message.js

Make exports across the codebase consistent

---

CHANGELOG.md
lib/editor/index.js

Remove tooltip on showTooltip config disable

---

CHANGELOG.md
lib/editor/index.js

Reason in code comment
Fixes #274

Remove tooltip on cursor change

---

README.md

It was a bit irritating so.. :stuck_out_tongue:

Fixed URL error in readme badge :P

---

lib/helpers.js
lib/tooltip/message-legacy.js

We broke it for several releases apparently
It didn't really work anyway so this is just code and UI cleanup

Remove link for message v1

---

CHANGELOG.md
package.json

Change statusBarRepresents default to Entire Project

---

CHANGELOG.md
lib/panel/dock.js
package.json

Readd panelHeight config

---

CHANGELOG.md
lib/panel/component.js

Fix clicking links in description

---

CHANGELOG.md
lib/status-bar/element.js
lib/status-bar/helpers.js
styles/linter-ui.less

Add icons to bottom status bar

---

styles/linter-ui.less

Tweak Tooltips UI

---

CHANGELOG.md
lib/editor/index.js
package.json

Add 'Both' to tooltipFollows

---

lib/panel/dock.js
lib/panel/index.js

Fix startup speed

---

CHANGELOG.md
lib/panel/index.js

Play safe in Dock

---

CHANGELOG.md
lib/panel/dock.js

Fix panel height config

---

CHANGELOG.md
lib/status-bar/index.js
package.json

Add click status bar to toggle scope behavior

---

CHANGELOG.md
lib/commands.js
lib/editors.js
lib/helpers.js
lib/panel/delegate.js
lib/panel/index.js
lib/status-bar/index.js
package.json

Don't know when the fix PR is gonna land but people's lives are uncomfortable because of this bug so figured would just fix it in my package
Related: #365
Fixes #363
Fixes #334

Fix Atom madness

---

CHANGELOG.md
lib/editor/index.js

Hide tooltip on cursor change for tooltipFollows Both

---

package.json

Update flow-bin to version 0.51.1 🚀

---

lib/helpers.js
lib/panel/delegate.js

Fix file scope for Linter panel as pane item

---

CHANGELOG.md
lib/panel/dock.js

Fix panel height inconsistency between panel and resize

---

lib/editor/index.js

Safeguard against https://github.com/atom/atom/issues/15341
In case the errorr really is on our side

Don't request mouse position of editor is disposed

---

CHANGELOG.md
package-lock.json
package.json

Make the changes necessary to get this ready for v1.6.9.

Prepare v1.6.9 release

---

lib/tooltip/fix-button.js
lib/tooltip/message.js
styles/linter-ui.less

Add a button to tooltip panel for fixing error,
if error could be fixed.
Just like `atom-ide-ui`

Add feature

---

.eslintrc.json
.flowconfig
lib/editors.js
lib/panel/component.js
lib/panel/delegate.js
lib/status-bar/index.js
lib/tooltip/message-legacy.js
lib/tooltip/message.js
lib/tree-view/index.js
package-lock.json
package.json
spec/editor-spec.js

chore(package): update eslint-config-steelbrain to version 4.0.1

---

.flowconfig
lib/index.js
lib/panel/component.js
lib/tooltip/message-legacy.js
lib/tooltip/message.js
lib/tree-view/index.js
package-lock.json
package.json

Updates `flow-bin` to version 0.64.0.
Fix the new Flow issues exposed by the updated version. Mostly this just entailed adding explicit types to the `React.Component` inheritance.
Closes #419.

Update flow-bin to version 0.64.0

---

CHANGELOG.md
lib/editor/index.js

Apply marker bug fix

---

lib/editor/index.js
lib/tree-view/index.js
package-lock.json
package.json

- uses lodash debounce instead of sb-debounce which is deprecated.
- npm audit fix

Use Lodash debounce instead of sb-debounce

---

lib/editors.js

Null check guard

---

lib/tooltip/message.tsx

Based on: https://nimblewebdeveloper.com/blog/convert-react-class-to-function-component

fix: convert MessageElement to functional component

---

styles/linter-ui.less

This fixes linter dock not scrolling
https://discord.com/channels/737254137690980372/737255015730774047/806537439400558602

fix: fix linter dock scroll

---

CHANGELOG.md
lib/tooltip/message.tsx
spec/fixtures/function-description.rb

feat: render descriptions correctly

---

lib/tooltip/message.tsx

It works for the ruby file with RuboCop

fix: make toggleDescription async

---

benchmark/benchmark.js
lib/commands.ts
lib/intentions.ts
lib/tooltip/message.tsx
spec/busy-singal-spec.js
spec/editor-spec.js

https://github.com/steelbrain/linter/issues/1705
https://github.com/steelbrain/linter/pull/1722

feat: allow solutions to be an async callback

---

lib/editors.ts
lib/helpers.ts
package.json
pnpm-lock.yaml

https://github.com/atom-community/atom-ide-base/blob/master/src-commons-atom/editor-largeness.ts

fix: use largeness from atom-ide-base
